[package]
name = "AdventOfCode"
version = "0.1.0"
authors = ["Bas Mulder <bas.d.mulder@gmail.com>"]

[dependencies]
reqwest = {version = "0.11"}
# aoc_util = { path = "./src/utils.rs" }

# [lib]
# path = "./src/lib.rs"

[[bin]]
name = "download"
path = "./download.rs"

